package.json, src/app/components/AddressContainer/index.tsx, src/app/containers/AddressContractDetail/AddressDetailPage.tsx, src/app/containers/AddressContractDetail/ContractDetailPage.tsx, src/app/containers/AddressContractDetail/ContractMetadata.tsx, src/app/containers/AddressContractDetail/Table.tsx, src/app/containers/HomePage/BlockchainInfo.tsx, src/app/index.tsx, src/setupProxy.js, src/utils/index.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/1)
=> feat: Compatible update

src/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/2)
=> feat: update version number

src/app/containers/Block/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/4)
=> fix: SCAN-3555

src/utils/constants.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/6)
=> feat: update testnet chainid condition

src/app/containers/ContractVerification/index.tsx, src/utils/hooks/usePortal.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/10)
=> feat: update style issue and reconnect wallet issue

src/app/components/Card/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/11)
=> feat: update card style issue

src/app/containers/NetworkError/index.tsx, src/app/containers/NotFoundAddressPage/__tests__/__snapshots__/index.test.tsx.snap, src/app/containers/NotFoundAddressPage/index.tsx, src/app/containers/NotFoundPage/__tests__/__snapshots__/index.test.tsx.snap, src/app/containers/NotFoundPage/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/13)
=> feat: update not found page style issue

src/app/components/AddressContainer/index.tsx, src/setupProxy.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/14)
=> feat: update mainnet address display

src/app/components/ConnectWallet/Modal.tsx, src/app/components/ConnectWallet/assets/metamask.svg, src/app/containers/Transaction/Detail.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/15)
=> fix: SCAN-3659, SCAN-3660

src/app/containers/AddressContractDetail/ContractMetadata.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/16)
=> feat: remove contract admin in contract detail

package.json, src/app/components/ContractAbi/index.tsx, src/app/containers/AddressContractDetail/ContractContent.tsx, src/setupProxy.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/17)
=> fix: fixed read&write proxy contract to address issue

package.json, src/app/components/Contract/index.tsx, src/app/components/ContractAbi/Func.tsx, src/app/components/TablePanelNew/index.tsx, src/app/containers/Accounts/index.tsx, src/app/containers/AddressContractDetail/ContractDetailPage.tsx, src/app/containers/AddressContractDetail/Table.tsx, src/app/containers/Header/index.tsx, src/app/containers/Swap/index.tsx, src/app/containers/TokenDetail/index.tsx, src/app/index.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json, src/setupProxy.js, src/styles/global-styles.ts, src/utils/gaConstants.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/19)
=> feat: release v1.1.0

src/app/containers/Transactions/CFXTxns.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/20)
=> fix: remove tx create type in tx transfer filter

src/app/containers/Notices/index.tsx, src/app/containers/Transactions/InternalTxns.tsx, src/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/22)
=> feat: release v1.1.1

src/app/components/TxnComponents/InputData/OptimizationDecode.tsx, src/app/components/TxnComponents/InputData/index.tsx, src/app/components/TxnComponents/util.ts, src/app/containers/Header/Search/index.tsx, src/app/containers/Transaction/EventLogs/Topics.tsx, src/app/containers/Transaction/EventLogs/index.tsx, src/setupProxy.js, src/utils/index.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/24)
=> feat: update s33 features

src/app/containers/Header/Search/index.tsx, src/app/containers/Notices/index.tsx, src/app/containers/Tokens/index.tsx, src/index.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json
hotfix token type typo issue of global search
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/26)
=> feat: release V1.2.1

package.json, src/app/components/ContractAbi/index.tsx, src/app/components/DownloadCSV/index.tsx, src/app/containers/Report/index.tsx, src/setupProxy.js, yarn.lock
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/27)
=> feat: 1. update google recapture sitekey 2. add batch request to contract read

src/app/containers/AddressContractDetail/TokenBalanceSelect.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/28)
=> feat: SCAN-3823, convert to hex address in token select of account page

src/app/containers/Transaction/Detail.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/31)
=> fix: fixed SCAN-3845

src/app/components/Description/__tests__/__snapshots__/index.test.tsx.snap, src/app/components/Footer/__tests__/__snapshots__/index.test.tsx.snap, src/app/components/NFTPreview/index.tsx, src/app/components/Nav/__tests__/__snapshots__/index.test.tsx.snap, src/app/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap, src/app/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap, src/app/containers/AddressConverter/__tests__/__snapshots__/index.test.tsx.snap, src/app/containers/NFTChecker/index.tsx, src/app/containers/NFTDetail/Loadable.tsx, src/app/containers/NFTDetail/TransferList.tsx, src/app/containers/NFTDetail/TransferModal.tsx, src/app/containers/NFTDetail/index.tsx, src/app/containers/NotFoundAddressPage/__tests__/__snapshots__/index.test.tsx.snap, src/app/containers/NotFoundPage/__tests__/__snapshots__/index.test.tsx.snap, src/app/containers/Notices/index.tsx, src/app/containers/PackingPage/__tests__/__snapshots__/index.test.tsx.snap, src/app/containers/Tokens/Transfers.tsx, src/app/containers/Transactions/CRC1155Txns.tsx, src/app/containers/Transactions/CRC721Txns.tsx, src/app/index.tsx, src/index.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json, src/styles/global-styles.ts, src/styles/media.ts, src/utils/httpRequest.ts, src/utils/tableColumns/token.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/32)
=> feat: release v1.3.0

src/app/containers/Transactions/InternalTxns.tsx
=> fix: show token name in internal txns list

src/app/containers/Footer/index.tsx, src/app/containers/Header/index.tsx, src/utils/index.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/34)
=> fix: fixed open api link issue

src/app/components/Charts/ChartTemplate.tsx, src/app/components/Charts/StockChartTemplate.tsx, src/app/containers/Charts/Wrapper.tsx, src/styles/global-styles.ts, src/utils/hooks/useHighcharts.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/41)
=> fix: fixed bugs

src/utils/constants.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/43)
=> fix: fixed openapi prefix

src/app/components/Text/index.tsx, src/app/containers/Notices/index.tsx, src/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/45)
=> fix: fixed tooltip title info click isse

src/app/containers/NFTAsset/index.tsx, src/app/containers/NFTDetail/index.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/46)
=> feat: add contract info to NFT detail

src/app/containers/Charts/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/47)
=> fix: fixed duration issue of charts

src/app/components/Text/index.tsx, src/app/containers/AddressContractDetail/TokenBalanceSelect.tsx, src/app/containers/NFTAsset/index.tsx, src/locales/zh_cn/translation.json, src/utils/constants.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/48)
=> feat: update i18n

src/setupProxy.js, src/utils/request.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/50)
=> feat: hotfix for evm open api compatible

src/app/containers/Notices/index.tsx, src/index.tsx, src/utils/request.ts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/51)
=> fix: update evmapi error handler

src/app/containers/NFTDetail/index.tsx, src/app/containers/Transaction/Detail.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json, src/utils/httpRequest.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/54)
=> feat: release NFT metadata refresh

src/app/components/NFTPreview/index.tsx, src/utils/request.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/55)
=> fix: fixed HEAD request issue

src/locales/zh_cn/translation.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/57)
=> feat: update miner zh i18n of top statistic

src/app/containers/Footer/index.tsx, src/utils/constants.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/58)
=> feat: update footer item

src/app/containers/Header/HeaderLink.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/60)
=> feat: change header link color on mobile platform

src/app/containers/ContractVerification/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/63)
=> fix: fixed null library issue when contract verify submit

src/app/containers/AddressContractDetail/ContractContent.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/66)
=> fix: fixed SDK init contract error

package.json, src/app/components/NFTPreview/3D.tsx, src/app/components/NFTPreview/index.tsx, src/app/containers/NFTDetail/index.tsx, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/68)
=> feat: update 3D component

src/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/sirius-eth/69)
=> feat: update version

src/app/containers/NFTDetail/index.tsx
=> feat: optimize NFT trait card style

src/app/containers/NFTDetail/index.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/72)
=> feat: update rights year

src/app/components/ConnectWallet/Button.tsx, src/app/components/ConnectWallet/useCheckHook.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/74)
=> fix: fixed connect wallet issue

src/app/containers/AddressContractDetail/ContractContent.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/76)
=> fix: fixed contract read issue

src/app/components/TxnComponents/GasFee.tsx, src/app/containers/Transaction/Detail.tsx, src/utils/index.ts, src/utils/tableColumns/block.tsx, src/utils/tableColumns/transaction.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/78)
=> feat: update gas price and gas fee unit

src/app/components/TxnComponents/GasFee.tsx, src/app/containers/Transaction/Detail.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/80)
=> feat: show full length gas fee value of tx detail

src/app/containers/AddressContractDetail/ContractContent.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/82)
=> feat: support show multiple verified sourcecode by hardhat compile

src/app/containers/Charts/CFXTransfer.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/86)
=> feat: update charts style

src/app/containers/Charts/CFXTransfer.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/87)
=> feat: update charts color

src/app/containers/AddressContractDetail/ContractContent.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/89)
=> fix: fixed contract verification view null issue

src/locales/en/translation.json, src/locales/zh_cn/translation.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/91)
=> feat: update Circulating Supply i18n

src/app/containers/AddressContractDetail/ContractMetadata.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/92)
=> fix: SCAN-4576, remove link if no token type

src/app/components/NFTPreview/index.tsx, src/app/containers/AddressContractDetail/AddressDetailPage.tsx, src/app/containers/AddressContractDetail/HeadLineButtons.tsx, src/app/containers/AddressContractDetail/IconButton.tsx, src/app/containers/AddressContractDetail/Table.tsx, src/app/containers/NFTAsset/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/94)
=> feat: optimized

src/app/containers/AddressContractDetail/Table.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/95)
=> feat: hide zero count tab by default of account detail page

src/app/containers/Footer/index.tsx, src/utils/hooks/useGetTxnStatus.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/97)
=> feat: update developer document link

src/app/components/Price/Loadable.ts, src/app/components/Price/index.tsx, src/app/containers/AddressContractDetail/TokenBalanceSelect.tsx, src/app/containers/TokenDetail/Basic.tsx, src/utils/constants.ts, src/utils/index.ts, src/utils/tableColumns/token.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/101)
=> feat: update price format

src/app/containers/Footer/index.tsx, src/utils/index.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/103)
=> feat: remove conflux truffle and studio link

src/app/containers/Transaction/Detail.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/105)
=> feat: hide NFTPreview if tranfer NFT to zeroAddress in tx detail

src/app/containers/Approval/Loadable.tsx, src/app/containers/Approval/NotFound.tsx, src/app/containers/Approval/index.tsx, src/app/containers/Header/index.tsx, src/app/index.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json, src/utils/constants.ts, src/utils/contract/ERC1155.json, src/utils/contract/ERC20.json, src/utils/contract/ERC721.json, src/utils/gaConstants.ts, src/utils/httpRequest.ts, src/utils/tableColumns/token.tsx, src/utils/tableColumns/utils.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/107)
=> feat: add token approvals

src/app/components/TablePanelNew/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/108)
=> fix: fixed approvals table total issue

src/app/containers/Approval/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/109)
=> fix: fixed auto connect issue of token approvals

src/app/components/AddressContainer/index.tsx, src/app/containers/AddressContractDetail/Nametag.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/112)
=> fix: SCAN-4619, SCAN-4620, SCAN-4621

src/app/containers/AddressContractDetail/Nametag.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/113)
=> fix: name tag labels length condition issue

src/app/components/TxnComponents/Status.tsx, src/app/containers/Transactions/ExcutedTxns.tsx, src/app/containers/Transactions/PendingTxns.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json, src/utils/httpRequest.ts, src/utils/tableColumns/PendingReason.tsx, src/utils/tableColumns/transaction.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/118)
=> feat: add pending txs

src/app/components/ContractAbi/ParamInput.tsx, src/utils/tableColumns/transaction.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/124)
=> fix: contract input placeholder

src/app/components/Charts/StockChartTemplate.tsx, src/app/components/ContractAbi/Func.tsx, src/app/components/ContractAbi/ParamInput.tsx, src/app/containers/Transaction/Detail.tsx, src/locales/en/translation.json, src/utils/index.ts, src/utils/tableColumns/transaction.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/125)
=> fix: improve pending view

src/app/components/Charts/StockChartTemplate.tsx, src/utils/index.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/126)
=> fix: charts hide animation

src/app/components/ContractAbi/OutputItem.tsx, src/utils/index.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/128)
=> fix: parse data in bytes format

src/app/components/Charts/StockChartTemplate.tsx, src/app/components/ContractAbi/OutputItem.tsx, src/utils/index.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/129)
=> Parse data in bytes format

src/app/containers/HomePage/BlockchainInfo.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/130)
=> feat: home add gasUsed

src/locales/en/translation.json, src/locales/zh_cn/translation.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/132)
=> fix: gasUsed translate

src/app/components/AddressContainer/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/133)
=> fix: support address array

src/app/components/AddressContainer/index.tsx, src/utils/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/134)
=> fix: bug caused by parsing byte

src/utils/constants.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/136)
=> feat: replacement RPC_URL

src/app/components/TxnComponents/NotApplicable.tsx, src/app/containers/HomePage/BlockchainInfo.tsx, src/setupProxy.js, src/utils/constants.ts, src/utils/request.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/139)
=> Fix bugs shine

src/app/containers/CFXTransfers/index.tsx, src/app/containers/Header/index.tsx, src/app/containers/NFTDetail/TransferList.tsx, src/app/containers/Transactions/CFXTxns.tsx, src/app/containers/Transactions/CRC1155Txns.tsx, src/app/containers/Transactions/CRC20Txns.tsx, src/app/containers/Transactions/CRC721Txns.tsx, src/locales/zh_cn/translation.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/142)
=> fix: optimize text, network icon

src/app/components/Charts/StockChartTemplate.tsx, src/locales/en/translation.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/143)
=> fix: optimize charts, Block Height

config-overrides.js, package.json, src/app/components/ConnectWallet/Balance.tsx, src/app/components/ConnectWallet/Button.tsx, src/app/components/ConnectWallet/History.tsx, src/app/components/ConnectWallet/Modal.tsx, src/app/components/ConnectWallet/index.tsx, src/app/components/ConnectWallet/useCheckHook.tsx, src/app/containers/Approval/index.tsx, src/app/containers/Swap/index.tsx, src/index.tsx, src/locales/en/translation.json, src/locales/zh_cn/translation.json, src/utils/chainManage.ts, src/utils/constants.ts, src/utils/hooks/usePortal.ts, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/151)
=> feat(wallet-connect): wallet connect optimize

package.json, src/app/components/Footer/index.tsx, src/app/containers/Footer/index.tsx, src/images/icon-add.svg, src/locales/en/translation.json, src/locales/zh_cn/translation.json, src/utils/chainManage.ts, src/utils/constants.ts, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/152)
=> feat(add network): add network

src/app/components/TransactionAction/index.tsx, src/app/components/TransactionAction/minibus.ts, src/app/containers/Tokens/index.tsx, src/utils/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/156)
=> fix: some bugs

src/app/components/AddressContainer/index.tsx, src/app/components/Charts/ChartTemplate.tsx, src/app/components/Charts/StockChartTemplate.tsx, src/app/components/TransactionAction/index.tsx, src/app/components/TransactionAction/minibus.ts, src/app/components/TxnComponents/Overview.tsx, src/app/containers/Tokens/index.tsx, src/app/containers/Transaction/Detail.tsx, src/utils/hooks/useHighcharts.ts, src/utils/index.ts, src/utils/tableColumns/transaction.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/157)
=> feat: Transaction action and fix some bugs.

package.json, src/env/bspace/devnet.js, src/env/env-constants.ts, src/env/espace/devnet.js, src/setupProxy.js, src/utils/constants.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/160)
=> feat: btc devnet update

src/app/components/NFTPreview/3D.tsx, src/app/components/NFTPreview/index.tsx, src/app/containers/NFTDetail/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/164)
=> fix: 3d render

src/app/components/AddressContainer/index.tsx, src/app/components/TransactionAction/index.tsx, src/app/components/TransactionAction/minibus.ts, src/app/components/TxnComponents/Overview.tsx, src/app/containers/Tokens/index.tsx, src/app/containers/Transaction/Detail.tsx, src/utils/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/165)
=> fix: fix some bugs

package.json, src/app/components/TransactionAction/index.tsx, src/utils/store.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/167)
=> fix: add nametag

src/app/components/AddressContainer/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/168)
=> fix: address isFullName

src/app/containers/Header/HeaderLink.tsx, src/app/containers/Header/index.tsx, src/app/index.tsx, src/utils/constants.ts, src/utils/hooks/useGlobal.ts, src/utils/index.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/170)
=> feat: network-switch ui refactor

src/utils/constants.ts, src/utils/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/173)
=> fix(configure 8889 rpc by hostname): configure 8889 rpc by hostname

src/env/bspace/devnet.ts, src/env/bspace/mainnet.ts, src/env/bspace/testnet.ts, src/setupProxy.js, src/utils/constants.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/172)
=> feat: bspace domain & add network

src/env/env-constants.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/175)
=> fix: env check

src/env/index.ts, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/176)
=> feat: default env

src/app/components/ConnectWallet/Link.tsx, src/app/components/ConnectWallet/Modal.tsx, src/app/components/Contract/index.tsx, src/app/components/DappButton/index.tsx, src/app/components/TabsTablePanel/Label.tsx, src/app/containers/BroadcastTx/index.tsx, src/app/containers/Charts/Wrapper.tsx, src/app/containers/GlobalNotify/index.tsx, src/app/containers/Profile/File.tsx, src/env/bspace/base.ts, src/env/bspace/devnet.ts, src/env/espace/base.ts, src/images/contract/upload.svg, src/styles/global-styles.ts, src/utils/constants.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/177)
=> fix: btc color

src/app/components/Charts/StockChartTemplate.tsx, src/app/containers/Charts/BlockTime.tsx, src/app/containers/Charts/Difficulty.tsx, src/app/containers/Charts/HashRate.tsx, src/app/containers/Charts/TPS.tsx, src/utils/hooks/useHighcharts.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/179)
=> fix: optimization Blockchain Data Charts

src/app/components/AddressContainer/index.tsx, src/app/components/ConnectWallet/Button.tsx, src/app/components/CookieTip/index.tsx, src/app/components/TxnComponents/AddressLabel.tsx, src/app/containers/AddressContractDetail/AddressDetailPage.tsx, src/app/containers/AddressContractDetail/ContractDetailPage.tsx, src/app/containers/Footer/Currency.tsx, src/app/containers/HomePage/BlockchainInfo.tsx, src/app/containers/Profile/AddressLabel.tsx, src/app/containers/Profile/CreateAddressLabel.tsx, src/app/containers/Profile/CreateTxNote.tsx, src/app/containers/Profile/File.tsx, src/app/containers/Profile/TxNote.tsx, src/app/containers/Transaction/Detail.tsx, src/app/index.tsx, src/env/bspace/devnet.ts, src/env/bspace/mainnet.ts, src/env/bspace/testnet.ts, src/env/env-constants.ts, src/env/espace/devnet.ts, src/env/espace/mainnet.ts, src/env/espace/testnet.ts, src/utils/constants.ts, src/utils/enum.ts, src/utils/hooks/useAge.ts, src/utils/hooks/useTxnHistory.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/182)
=> feat: api host

src/app/components/DappButton/index.tsx, src/app/containers/Header/HeaderLink.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/183)
=> fix: styled-components error

src/utils/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/184)
=> fix: roundToFixedPrecision unit lost

src/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/187)
=> fix: react dom renderr

package.json, src/app/containers/NetworkError/index.tsx, src/env/env-constants.ts, src/utils/constants.ts, src/utils/index.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/185)
=> fix: env error

src/env/bspace/devnet.ts, src/env/espace/devnet.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/190)
=> feat: devnet fix

src/app/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/191)
=> change layout loading

config-overrides.js, src/app/containers/Charts/BlockTime.tsx, src/app/containers/Charts/TPS.tsx, src/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/193)
=> feat: pull out charts testing

config-overrides.js, package.json, src/app/containers/NFTDetail/index.tsx, src/utils/httpRequest.ts, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/195)
=> feat: metadata backup

src/app/components/ConnectWallet/Modal.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/203)
=> fix: connect-wallet

src/app/components/TxnComponents/util.ts, src/app/containers/Transaction/EventLogs/Data.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/206)
=> fix eventlog undefined data

src/app/containers/Charts/Difficulty.tsx, src/app/containers/Charts/HashRate.tsx, src/app/containers/HomePage/BlockchainInfo.tsx, src/utils/constants.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/207)
=> fix: block time

src/app/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/209)
=> fix: remove loading after fetch

src/app/containers/AddressContractDetail/ContractDetailPage.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/212)
=> fix: contract name

src/utils/tableColumns/transaction.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/215)
=> fix: verified logic

src/utils/tableColumns/transaction.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/217)
=> fix: verify is null

src/app/containers/AddressContractDetail/ContractMetadata.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/219)
=> fix: loading parse

config-overrides.js
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/223)
=> fix: react-i18next

src/app/components/NFTPreview/index.tsx, src/app/containers/NFTDetail/index.tsx, src/app/containers/NetworkError/index.tsx, src/utils/tableColumns/utils.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/228)
=> fix: tooltip style

src/app/components/TablePanelNew/index.tsx, src/app/containers/AddressContractDetail/Table.tsx, src/app/containers/CFXTransfers/index.tsx, src/app/containers/Header/index.tsx, src/app/containers/NFTDetail/Holders.tsx, src/app/containers/NFTDetail/TransferList.tsx, src/app/containers/TokenDetail/Holders.tsx, src/app/containers/Tokens/Transfers.tsx, src/app/containers/Transactions/CFXTxns.tsx, src/app/containers/Transactions/CRC1155Txns.tsx, src/app/containers/Transactions/CRC20Txns.tsx, src/app/containers/Transactions/CRC721Txns.tsx, src/app/containers/Transactions/InternalTxns.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/231)
=> fix: remove code

package.json, src/app/containers/Header/Search/index.tsx, src/app/index.tsx, src/utils/hooks/useSearch.ts, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/235)
=> fix: url address simply converted checksum

.eslintrc.js, package.json, src/utils/index.ts, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/236)
=> fix: address type

src/app/components/StatsCard/NetworkPie.tsx, src/app/containers/Accounts/index.tsx, src/app/containers/Approval/index.tsx, src/utils/tableColumns/account.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/241)
=> fix: checksum hex leak

package.json, src/app/containers/Transaction/Detail.tsx, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/242)
=> feat: next version & isCorssSpaceCall

package.json, src/app/containers/Charts/cip1559Metrics/AveragePriorityFeePerBlock.tsx, src/app/containers/Charts/cip1559Metrics/BaseFeePerBlock.tsx, src/app/containers/Charts/cip1559Metrics/GasUsedPerBlock.tsx, src/app/containers/Charts/cip1559Metrics/PercentageOfTxTypeInBlock.tsx, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/245)
=> fix: xAxis

src/app/containers/Block/DescriptionPanel.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/247)
=> fix: hover pivot height

src/app/containers/Block/DescriptionPanel.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/250)
=> fix: only core block

package.json, src/app/containers/Transaction/Detail.tsx, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/251)
=> fix: hide tooltip

package.json, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/252)
=> fix: hex2asc

src/utils/tableColumns/block.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/253)
=> fix: show Inapplicable in core block

src/app/components/TransactionAction/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/255)
=> fix: decaimals

src/app/components/TxnComponents/Overview.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/256)
=> fix: prioritize using tokenTransferTokenInfoList

src/app/containers/Transaction/Detail.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/259)
=> fix: gasFee

src/app/components/StatsCard/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/261)
=> fix: corrected Top Statistics text

src/app/containers/Charts/cip1559Metrics/AveragePriorityFeePerBlock.tsx, src/app/containers/Charts/cip1559Metrics/BaseFeePerBlock.tsx, src/app/containers/Charts/cip1559Metrics/GasUsedPerBlock.tsx, src/app/containers/Charts/cip1559Metrics/PercentageOfTxTypeInBlock.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/262)
=> fix: rm dayjs utc

package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/264)
=> fix(update common version): ()

src/app/containers/Transaction/Detail.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/269)
=> fix: attr tag wrap

package.json, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/272)
=> feat: update next version

src/app/containers/Block/DescriptionPanel.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/275)
=> fix: gasLimit & gasUsed display

src/app/components/TablePanelNew/index.tsx, src/app/containers/Tokens/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/277)
=> fix: table sort

package.json, src/app/components/ConnectWallet/Modal.tsx, src/app/components/Contract/index.tsx, src/app/components/StatsCard/index.tsx, src/app/containers/Accounts/index.tsx, src/app/containers/Approval/index.tsx, src/app/containers/Charts/Token.tsx, src/app/containers/NFTDetail/TransferModal.tsx, src/app/containers/TokenDetail/index.tsx, src/utils/index.ts, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/280)
=> Fix  base32 to hex

README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/284)
=> docs: add build & config readme

src/app/containers/Footer/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/286)
=> fix: update footer link

package.json
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/285)
=> feat: remove unused scripts

README.md, src/env/bspace/devnet.ts, src/env/bspace/mainnet.ts, src/env/bspace/testnet.ts, src/env/espace/devnet.ts, src/env/espace/mainnet.ts, src/env/espace/testnet.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/289)
=> feat: remove unused config

src/app/containers/TokenDetail/index.tsx, src/utils/tableColumns/token.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/290)
=> fix: transfer type

package.json, src/app/containers/TokenDetail/index.tsx, src/utils/tableColumns/token.tsx, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/291)
=> Temp release

src/app/containers/Transactions/components/AdvancedSearchForm.tsx, src/app/containers/Transactions/components/DebounceTokenSelect.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/297)
=> fix: dayjs

package.json, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/298)
=> fix: update use-wallet version

src/app/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/299)
=> fix: frontend api

src/app/containers/Charts/cip1559Metrics/AveragePriorityFeePerBlock.tsx, src/app/containers/Charts/cip1559Metrics/BaseFeePerBlock.tsx, src/app/containers/Charts/cip1559Metrics/GasUsedPerBlock.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/301)
=> fix: prettier

src/app/components/TablePanelNew/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/302)
=> fix: csv download

src/app/components/TablePanelNew/index.tsx, src/app/containers/AddressContractDetail/ContractDetailPage.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/306)
=> fix: refresh table data while table url changed

src/app/containers/Block/DescriptionPanel.tsx, src/app/containers/Block/index.tsx, src/app/containers/Transaction/Detail.tsx, src/app/containers/Transaction/index.tsx, src/utils/api.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/307)
=> fix: duplicate request

src/app/containers/Transaction/Detail.tsx, src/utils/tableColumns/utils.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/309)
=> fix: age render

src/app/containers/Block/DescriptionPanel.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/311)
=> fix: 1559 block display

package.json, src/app/containers/AddressContractDetail/AddressDetailPage.tsx, src/app/containers/Approval/index.tsx, src/app/containers/ContractVerification/index.tsx, src/app/containers/NFTAsset/index.tsx, src/app/containers/NFTChecker/index.tsx, src/app/containers/Transactions/components/AdvancedSearchForm.tsx, src/app/index.tsx, src/utils/hooks/useSearch.ts, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/315)
=> fix: core space format address detail

src/app/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/318)
=> fix: unused-vars

package.json, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/324)
=> feat: fix google recaptcha

package.json, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/325)
=> feat: next version

package.json, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/329)
=> fix: i18n typo

src/app/components/ContractAbi/Func.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/332)
=> fix: contract input parse

package.json, src/app/containers/Transaction/Detail.tsx, src/app/containers/Transaction/EventLogs/Address.tsx, src/app/containers/Transaction/EventLogs/StyledComponents.tsx, src/app/containers/Transaction/EventLogs/Topics.tsx, src/env/bspace/base.ts, src/env/espace/base.ts, src/styles/global-styles.ts, src/utils/tableColumns/token.tsx, src/utils/tableColumns/transaction.tsx, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/334)
=> feat: highlight

package.json, src/app/containers/Transactions/index.tsx, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/336)
=> update sirius-next version

src/app/containers/Transactions/ExcutedTxns.tsx, src/app/containers/Transactions/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/338)
=> fix: columns width

src/env/index.ts, src/types/global.d.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/340)
=> feat: add window.customConfig

src/app/components/ContractAbi/Func.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/346)
=> feat: write contract from param

src/utils/constants.ts
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/348)
=> fix: from params

package.json, src/utils/api.ts, src/utils/hooks/useTableDataByHttp.ts, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/351)
=> fix: query-string

src/app/containers/HomePage/BlockchainInfo.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/352)
=> fix: request core plot data

src/app/components/TablePanelNew/index.tsx, src/app/containers/Transactions/CFXTxns.tsx, src/app/containers/Transactions/CRC1155Txns.tsx, src/app/containers/Transactions/CRC20Txns.tsx, src/app/containers/Transactions/CRC721Txns.tsx, src/app/containers/Transactions/ExcutedTxns.tsx, src/utils/tableColumns/token.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/355)
=> feat: phishing address

package.json, yarn.lock
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/357)
=> fix: cns i18n

package.json, src/utils/index.ts, yarn.lock
=> feat: optimize evm address type

src/app/containers/ABIVerification/index.tsx, src/app/containers/Transactions/ExcutedTxns.tsx, src/app/containers/Transactions/index.tsx, src/utils/tableColumns/transaction.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/364)
=> fix: columns width & reset txData after submit

src/app/components/TxnComponents/InputData/index.tsx, src/app/containers/Transaction/EventLogs/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/365)
=> fix: use abi while contract is verified

src/app/containers/Transaction/index.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/370)
=> fix: label

src/utils/tableColumns/authorizations.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/371)
=> fix: tooltip in table

src/app/containers/Transaction/AuthorizationList.tsx
=> fix: remove age column

src/app/containers/AddressContractDetail/ContractContent.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/377)
=> feat: add vyper contract info display

src/app/containers/ContractVerification/Step2.tsx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Conflux-Chain/sirius-eth/379)
=> fix: file upload error
